[target.x86_64-pc-windows-msvc]
rustflags = [
    "-C", "link-arg=/STACK:8000000",
    "-C", "link-arg=/FORCE:MULTIPLE"
]

[target.aarch64-pc-windows-msvc]
rustflags = [
    "-C", "link-arg=/STACK:8000000",
    "-C", "link-arg=/FORCE:MULTIPLE"
]